import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <aside className="fixed z-40 top-0 left-0 h-screen outline-dashed">
          <h1>Navbar</h1>
        </aside>
        <div className="rounded-lg outline-dashed mt-10 mx-2 md:mx-40 p-5">
          {children}
        </div>
      </body>
    </html>
  );
}
